In [ ]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [ ]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
)

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.drop(columns=["id", "Unnamed: 32"], axis=1, inplace=True)

In [ ]:
df.value_counts(df.columns[0])

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [ ]:
# split the data
X_train, X_test, y_train, y_test = train_test_split(
    df.drop(columns=["diagnosis"]), df["diagnosis"], test_size=0.2
)

In [ ]:
# scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.51753759,  1.71852214, -0.45649873, ...,  0.44965654,
         0.48719651,  2.00875502],
       [-1.27217218, -0.28112332, -1.27900393, ..., -1.39518958,
         0.22951142, -0.31018391],
       [-0.80278494, -1.18050724, -0.83970673, ..., -1.60714088,
        -0.25813314, -1.13722584],
       ...,
       [-0.33113832,  0.33064036, -0.35987791, ..., -0.81594757,
         0.45620906, -1.11000955],
       [-0.05436366,  0.06584712, -0.04831671, ...,  1.01119779,
         0.42848345,  1.17560331],
       [ 0.19416869, -0.54591656,  0.10603096, ..., -0.56035475,
        -0.6381371 , -0.89227923]])

In [ ]:
X_test

array([[ 1.47636968,  0.95153484,  1.50662343, ...,  0.6098789 ,
         0.00607562, -0.4551523 ],
       [-0.681343  , -0.27199252, -0.70828603, ..., -0.68410745,
        -1.5302494 , -0.843401  ],
       [ 1.51308469, -0.0985073 ,  1.52299984, ...,  1.24466466,
         0.0843597 ,  0.8306785 ],
       ...,
       [ 1.15158309,  0.14802434,  1.11768369, ...,  1.17142015,
         0.23929693, -0.03635471],
       [-2.03104312, -1.34714436, -1.98605543, ..., -1.77667141,
         0.02564664,  0.52685584],
       [ 0.47376759,  1.05425636,  0.46672139, ..., -0.06915875,
        -0.17495631, -1.19221385]])

In [ ]:
# label encode the target variable
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [ ]:
# convert to tensors
X_train_tensor = torch.from_numpy(X_train.astype("float32"))
X_test_tensor = torch.from_numpy(X_test.astype("float32"))
y_train_tensor = torch.from_numpy(y_train.astype("float32"))
y_test_tensor = torch.from_numpy(y_test.astype("float32"))

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

# defining the model

In [ ]:
import torch.nn as nn


class MySimpleNN(nn.Module):
    # old way of defining a model without nn.Module
    # def __init__(self, X):
    #     self.weights = torch.randn(
    #         X.shape[1], 1, requires_grad=True, dtype=torch.float64
    #     )
    #     self.bias = torch.zeros(1, requires_grad=True, dtype=torch.float64)

    # # forward pass
    # def forward(self, X):
    #     z = torch.matmul(X_train_tensor, self.weights) + self.bias
    #     y_pred = torch.sigmoid(z)
    #     return y_pred

    # loss function
    # new way of defining a model with nn.Module
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

        # def loss_function(self, y_pred, y):
        #     epsilon = 1e-7
        #     y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        #     loss = -(
        #         y_train_tensor * torch.log(y_pred)
        #         + (1 - y_train_tensor) * torch.log(1 - y_pred)
        #     ).mean()
        # return loss

In [ ]:
# Important Parameters

learning_rate = 0.1
epochs = 25

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
# training Pipeline

model = MySimpleNN(X_train_tensor.shape[1])
# model.weight

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.0724,  0.0281, -0.0307, -0.0496, -0.0254, -0.1606, -0.0180,  0.0245,
          0.1408,  0.0788,  0.1351,  0.0965, -0.0672,  0.0048,  0.0439, -0.1027,
         -0.0843, -0.0492,  0.1666, -0.1087,  0.1042,  0.0102,  0.1805,  0.1637,
          0.1622, -0.1278,  0.1213, -0.1731,  0.1042, -0.0787]],
       requires_grad=True)

In [ ]:
# model.bias

In [ ]:
X_train_tensor.shape[1]

30

In [ ]:
y_train_tensor.view(-1, 1).shape

torch.Size([455, 1])

In [ ]:
y_pred.shape

torch.Size([114, 1])

In [ ]:
# define the loop
for epoch in range(epochs):

    # forward pass
    y_pred = model(X_train_tensor)

    # loss function
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # opitmization step with optim

    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

    # zero the gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update

    optimizer.step()

    # # manual way to update weights
    # with torch.no_grad():
    #     model.linear.weight -= learning_rate * model.linear.weight.grad
    #     model.linear.bias -= learning_rate * model.linear.bias.grad

    # manual way of zeroing the gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    # print loss every epochs
    print(f"Epoch {epoch+1}: loss = {loss.item()}")

Epoch 1: loss = 0.65602046251297
Epoch 2: loss = 0.49471306800842285
Epoch 3: loss = 0.408467173576355
Epoch 4: loss = 0.35513442754745483
Epoch 5: loss = 0.3186216652393341
Epoch 6: loss = 0.29185807704925537
Epoch 7: loss = 0.271268367767334
Epoch 8: loss = 0.2548483908176422
Epoch 9: loss = 0.24138565361499786
Epoch 10: loss = 0.23010241985321045
Epoch 11: loss = 0.22047606110572815
Epoch 12: loss = 0.21214184165000916
Epoch 13: loss = 0.2048371136188507
Epoch 14: loss = 0.19836772978305817
Epoch 15: loss = 0.19258670508861542
Epoch 16: loss = 0.18738074600696564
Epoch 17: loss = 0.18266086280345917
Epoch 18: loss = 0.17835621535778046
Epoch 19: loss = 0.17440947890281677
Epoch 20: loss = 0.1707739233970642
Epoch 21: loss = 0.16741085052490234
Epoch 22: loss = 0.1642879992723465
Epoch 23: loss = 0.16137820482254028
Epoch 24: loss = 0.15865842998027802
Epoch 25: loss = 0.15610893070697784

In [ ]:
# model evaluation
with torch.no_grad():
    y_pre = model.forward(X_test_tensor)
    y_pre = torch.where(y_pre > 0.5, 1, 0)

accuracy = (y_pre == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()*100:.2f}%")

Accuracy: 55.26%

In [ ]:
y_pre

tensor([[1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1]])

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1655,  0.1841,  0.2086,  0.1747,  0.0436, -0.0069,  0.1920,  0.2595,
          0.1765,  0.0228,  0.2876,  0.0625,  0.0818,  0.1625, -0.0013, -0.0437,
         -0.0323,  0.0460,  0.0858, -0.1259,  0.3578,  0.1942,  0.4347,  0.3951,
          0.2961,  0.0678,  0.3541,  0.0958,  0.2186,  0.0278]],
       requires_grad=True)

In [ ]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item()*100:.2f}%")

Accuracy: 58.86%